* resources
QAM constellation shapes
https://www.electronics-notes.com/articles/radio/modulation/quadrature-amplitude-modulation-types-8qam-16qam-32qam-64qam-128qam-256qam.php
* public signals info
   Symbol Rate (MHz) Modulation Type Modulation Order
0                  5             PSK             BPSK
1              21.26             PSK             QPSK
2                 25             QAM            QAM16
3              13.11             QAM            QAM32
4              30.73             QAM            QAM64
5               None             PSK             BPSK
6               None            None             None
7               None            None             None
8               None             PSK             QPSK
9                  5             PSK             BPSK
10              None            None             None
11              None             PSK             QPSK
12             12.05             QAM            QAM64
13              None            None             None
14              None            None             None
15              None            None             None
16              1.52             QAM            QAM16
17              None            None             None
18              None             PSK             QPSK

* additional info
nos: oversampling factor
phases: phase (in samples) needed for correct sampling

Signal 0
nos: 20
phase: 10

Signal 1
nos: 4.703668861712136
phase: 5.5 (or probably 1 as well)

Signal 2
nos: 4
phase: 3

* OLD additional info
[2021-05-12 Wed] Update: I wasn't separating sigI and sigQ correctly so the below phase values are probably incorrect now.

Signal 1
nos: 4.703668861712136
phase: 5 (or probably/maybe 0 as well)

Signal 2
nos: 4
phase: 3 (or probably 2 as well)

Signal 3
nos: 7.627765064836003
phase: 4 or 5 look good. Though interestingly 12 looks best.
TODO maybe this suggests that I should look for much larger phases?
Or PERHAPS that I need to do some sort of interpolation?

Signal 4
nos: 3.254149040026033
phase: 3 (or probably/maybe 2 as well)

Signal 9
nos: 20
phase: 13 (or MAYBE 14 as well)

Signal 12
nos: 8.298755186721992
phase: 4 (or very probably 5 as well)

Signal 16
nos: 65.78947368421052
phase: 29
* missing parameters
0                  5          BPSK
1              21.26          QPSK
2                 25         QAM16
3              13.11         32QAM
4              30.73         QAM64
*5               7.79         BPSK
*6              15.66        32QAM

AWGN
*7              15.75        16QAM
*8               8.23         QPSK
9                   5         BPSK
*10              20.0        64QAM

PHASE DRIFT
*11             17.82         QPSK
12              12.05         QAM64
*13              33.2         32QAM
*14               5.0         BPSK

CW
***15             5.0         BPSK
16               1.52        QAM16
?***17           31.99         None
?***18           18.32        QPSK

17 --> maybe 10 MHz?
18 --> maybe 9.2 MHz?
* finals signal set
index        freq (MHz)     mod                   sampling offset
0            40             64QAM                 0.5855
1            40             16QAM                 0.8449 (var: 0.00164)
2            31.25          32QAM (probably)      0.5123
3            12.5           64QAM
4            25             16QAm
* samples files
8 samples missing (4 from start, 4 at end)

